//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaShopFinal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PizzaShopEntities : DbContext
    {
        public PizzaShopEntities()
            : base("name=PizzaShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MenuPizza> MenuPizza { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<ShoppingBasket> ShoppingBasket { get; set; }
        public virtual DbSet<SizePizza> SizePizza { get; set; }
        public virtual DbSet<typeDoughPizza> typeDoughPizza { get; set; }
    }
}
